---
- hosts: all
  become: true
  tasks:
    - name: copy file in tmp
      copy: src=enlinuxpc64 dest=/tmp/
    - name: create direcctory
      file: path=/usr/local/encase state=directory
    - name: copyfile in tmp to encase
      copy: src=enlinuxpc64 dest=/usr/local/encase
    - name: give permission
      raw: chown root:root /usr/local/encase/enlinuxpc64
    - name: change file permisions
      command: chmod 755 /usr/local/encase/enlinuxpc64
      command: /usr/local/encase/enlinuxpc64 -d -l 4445 state=install
      command: /usr/local/encase/enlinuxpc64 -d -l 4446 state=install
